name: Test Before Commit
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pulling code..."
      - name: Get code
        uses: actions/checkout@v3
      - run: echo "Installing NodeJS..."
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: echo "Installing dependencies..."
      - name: Install Dependencies
        run: npm ci
      - name: Run test
        run: npm test